# اضافه کردن کتابخانه

In [1]:
import numpy as np

# ورژن و تنظیمات کتابخانه

In [2]:
print(np.__version__)
np.show_config()

2.0.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-2iyom4cp/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

d:\code\venvdatascience\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


# ایجاد بردار خالی

In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


python -c "import numpy; numpy.info(numpy.add)

# تغییر یک عدد از بردار

In [4]:
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# ساخت بردار با یک رنج عددی خاص

In [5]:
z=np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# ساخت بردار با رنج رو به پایین

In [6]:
z=np.arange(50)
z=z[::-1]
z


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
nz= np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [9]:
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
z=np.random.random((3,3,3))
z

array([[[0.03348207, 0.40933011, 0.88419559],
        [0.2666634 , 0.67760725, 0.33882271],
        [0.9316675 , 0.67551897, 0.6427328 ]],

       [[0.2246578 , 0.46817059, 0.10948666],
        [0.27943876, 0.42049744, 0.47609666],
        [0.529801  , 0.00875095, 0.79598401]],

       [[0.55293239, 0.39863916, 0.79187549],
        [0.71403534, 0.41694416, 0.51431255],
        [0.67718743, 0.09579673, 0.1256628 ]]])

In [11]:
z=np.random.random((10,10))
Zmin,Zmax =z.min(),z.max()
print(z)
print(Zmin,Zmax)


[[0.58547199 0.70196283 0.10680893 0.32557297 0.49467637 0.98864092
  0.37491611 0.15768898 0.03106766 0.4077464 ]
 [0.84663955 0.86471092 0.18589282 0.04925654 0.53019621 0.19169276
  0.64250547 0.50123606 0.18031732 0.61665297]
 [0.74276772 0.77934372 0.86698715 0.92514508 0.31381294 0.26104455
  0.86825953 0.83151749 0.790708   0.88383119]
 [0.21516139 0.84524088 0.46338376 0.00646049 0.28601197 0.26049165
  0.33533871 0.53180258 0.50772664 0.02070472]
 [0.13623034 0.3659342  0.99700119 0.52194083 0.66706124 0.00269763
  0.48612215 0.98294073 0.57398318 0.24118941]
 [0.00291653 0.3243503  0.94100787 0.52588817 0.31824619 0.94325509
  0.47723327 0.62133914 0.10515836 0.30344723]
 [0.97688133 0.03312617 0.78423244 0.21986331 0.75493092 0.76879075
  0.86467624 0.53917923 0.45869505 0.5701485 ]
 [0.75224442 0.87371738 0.00980341 0.37700807 0.36580383 0.12964257
  0.45988418 0.84303133 0.36397953 0.25146684]
 [0.68306708 0.21899165 0.85288686 0.96366271 0.712769   0.93165266
  0.21987205

In [12]:
z=np.random.random(30)
m=z.mean()
m

np.float64(0.5161511807755512)

In [13]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
z


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1

False

In [15]:
z= np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [16]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [17]:
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


In [18]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# ساخت یک ماتریکس راندوم و نرمالایز کردن داده هایش

In [19]:
z= np.random.random((5,5))
zmax,zmin =z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
z

array([[0.99899012, 0.17888642, 0.75172281, 0.82210278, 0.16422085],
       [0.26982122, 0.85492304, 0.09181346, 0.6936746 , 0.56706876],
       [0.27587856, 0.24219233, 0.10819797, 0.22467894, 0.58119505],
       [1.        , 0.13010061, 0.81911805, 0.        , 0.10760664],
       [0.81928894, 0.6771609 , 0.78313617, 0.38768586, 0.27828527]])

In [20]:
color = np.dtype([('r',np.ubyte,1),
                  ('g',np.ubyte,1),
                  ('b',np.ubyte,1),
                  ('a',np.ubyte,1)])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

In [21]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [22]:
z=np.arange(11)
z[(3<z)& (z<=8)]+= -1
z

array([ 0,  1,  2,  3,  3,  4,  5,  6,  7,  9, 10])

In [23]:
print (sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [24]:
z**z
2<< z>>2
z<- z
1j*z
z/1/1
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
n1=np.array(0)//np.array(0)
n2=np.array(0)//np.array(0.)
n3=np.array(0)/np.array(0)
n4=np.array(0)/np.array(0.)
n1,n2,n3,n4


C:\Users\vahid\AppData\Local\Temp\ipykernel_20112\4152855563.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  n1=np.array(0)//np.array(0)
C:\Users\vahid\AppData\Local\Temp\ipykernel_20112\4152855563.py:2: RuntimeWarning: invalid value encountered in floor_divide
  n2=np.array(0)//np.array(0.)
C:\Users\vahid\AppData\Local\Temp\ipykernel_20112\4152855563.py:3: RuntimeWarning: invalid value encountered in divide
  n3=np.array(0)/np.array(0)
C:\Users\vahid\AppData\Local\Temp\ipykernel_20112\4152855563.py:4: RuntimeWarning: invalid value encountered in divide
  n4=np.array(0)/np.array(0.)


(np.int64(0), np.float64(nan), np.float64(nan), np.float64(nan))

In [26]:
z=np.random.uniform(-10,+10,10)
print(np.trunc(z+np.copysign(0.5,z)))

[-2. -1. -6.  7.  6. -8. -7.  6.  1.  2.]


In [27]:
z=np.random.uniform(0,10,10)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[7. 0. 9. 6. 6. 0. 5. 7. 4. 2.]
[7. 0. 9. 6. 6. 0. 5. 7. 4. 2.]
[7. 0. 9. 6. 6. 0. 5. 7. 4. 2.]
[7 0 9 6 6 0 5 7 4 2]
[7. 0. 9. 6. 6. 0. 5. 7. 4. 2.]


# یک ماتریکس 5در5 ایجاد کنید که اعداد آن بین صفر تا چهار باشد

In [28]:
z=np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [31]:

def generate ():
    for x in range(10):
        yield x
z=np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [34]:
z= np.linspace(0,1,12,endpoint=True)[1:-1]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [35]:
z = np.random.random(10)
z.sort()
z

array([0.11627307, 0.12006012, 0.20092348, 0.29874486, 0.49662719,
       0.5282702 , 0.61331985, 0.71627191, 0.88143719, 0.93993277])

In [38]:
z=np.arange(10)
np.add.reduce(z)


np.int64(45)

In [39]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
equal

False

# تبدیل داده ها به فقط خواندنی

In [40]:
z=np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [44]:
z=np.random.random((10,2))
X,Y=z[:,0],z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.82195076 1.25236778 1.30593622 0.92251153 0.92592488 0.80173396
 0.74029623 0.07162191 1.04758125 1.10599231]
[0.76775634 0.86994785 0.71481961 0.53407318 0.38059401 0.96053407
 1.29238348 0.12755913 0.78859628 0.53446821]
