In [2]:
import numpy as np


#array

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

#matrix

In [6]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

##shape

In [7]:
print(a.shape,b.shape)

(4,) (2, 2)


reshape

In [12]:
c=a.reshape([4,1])
c

array([[1],
       [2],
       [3],
       [4]])

In [13]:
print(c.shape)

(4, 1)


تبدیل به تنسور

In [14]:
d=a.reshape(2,2,1)
d

array([[[1],
        [2]],

       [[3],
        [4]]])

وقتی یک عدد رو نمی دونیم اگر 1-بزاریم خودش اون رو حساب میکنه

In [16]:
d=a.reshape(2,-1,1)
print(d.shape)

(2, 2, 1)


چسباندن دوتا لیست به هم
concatenate

In [18]:
a=np.array([1,4,5,6,7,8,9])
b=np.array([45,2,25,3,2,44,5])
c=np.concatenate([a,b])
c

array([ 1,  4,  5,  6,  7,  8,  9, 45,  2, 25,  3,  2, 44,  5])

کار با عملگرهای ریاضی

In [20]:
d=a+b
e=a-b
f=a*b
g=a/b
h=a%b
d,e,f,g,h

(array([46,  6, 30,  9,  9, 52, 14]),
 array([-44,   2, -20,   3,   5, -36,   4]),
 array([ 45,   8, 125,  18,  14, 352,  45]),
 array([0.02222222, 2.        , 0.2       , 2.        , 3.5       ,
        0.18181818, 1.8       ]),
 array([1, 0, 5, 0, 1, 8, 4]))

به تعداد ایندکس ها کاری ندارد برابر است یا نه 
دو طرف را با هم محاسبه میکند


In [21]:
k=np.array([5])
l=a+k
l

array([ 6,  9, 10, 11, 12, 13, 14])

broadcastکردن یک لیست 

In [22]:
m=a+5
m

array([ 6,  9, 10, 11, 12, 13, 14])

انتخاب بخش خاصی از یک لیست
slice

listname[start:end:step]

In [23]:
a=np.array([1,2,4,5,6,7,8,9,0])
b=a[3:6:1]
b

array([5, 6, 7])

قرار دادن شرط 

In [24]:
b=a[a<5]
b

array([1, 2, 4, 0])

#کار با توابع ریاضی

In [25]:
a

array([1, 2, 4, 5, 6, 7, 8, 9, 0])

In [32]:
sum_a = np.sum(a)
max_a=np.max(a)
min_a=np.min(a)
sum_a,max_a,min_a

(np.int64(42), np.int64(9), np.int64(0))

مرتب کردن از کوچک به بزرگ


In [33]:
a_sort=np.sort(a)
a_sort

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

ساخت یک ماتریس راندوم

np.random.randint[start,end,size]

In [34]:
a= np.random.randint(-10,20,(5,6))
a

array([[-4, 18, -5, -4, 12, 15],
       [ 3,  4,  3, -2,  1, 19],
       [-7, 12, -2, 18, 15, -3],
       [-6, -2,  2, -6, -3, -7],
       [-4,  6,  0, 15, -2,  4]], dtype=int32)

stackکردن دوتا آرایه با هم 
یعنی روی هم قرار دادن داده ها به طوری که هرکدام در یک سطر باشد

In [38]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
d=np.hstack([a,b])
d

array([1, 2, 3, 4, 5, 6])

در ماشین لرنینگ خیلی مهمه این مورد

normalize

محاسبه میانگین لیست
np.mean(list)

In [41]:
a=np.array([12,34,56,32,34,46,99,31])
mean_a=np.mean(a)
mean_a

np.float64(43.0)

محاسبه انحراف از معیار

np.std(list)

In [42]:
stdlist=np.std(a)
stdlist

np.float64(24.243555844801314)

normalize کردن

یعنی میانگین رو به سمت صفر میل بدیم و انحراف از معیار رو به سمت یک 

In [43]:
norm_a= (a-mean_a)/stdlist
norm_a

array([-1.27869031, -0.37123267,  0.53622497, -0.45372882, -0.37123267,
        0.12374422,  2.30989218, -0.4949769 ])

In [44]:
mean_end=np.mean(norm_a)
std_end=np.std(norm_a)
mean_end,std_end

(np.float64(2.7755575615628914e-17), np.float64(1.0))

In [2]:
import numpy as np
data1=np.arange(1,10)
data2=np.arange(2,20,3)
data3=np.arange(1.5,2.5,0.1)
print(data1)
print(data2)
print(data3)


[1 2 3 4 5 6 7 8 9]
[ 2  5  8 11 14 17]
[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]
