<a href="https://colab.research.google.com/github/shabanvahid0101/python_gram_file/blob/main/tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [3]:
print(tf.test.gpu_device_name())

/device:GPU:0


# اعداد به صورت عادی شیپ ندارد

In [4]:
a=tf.constant(6)
a

<tf.Tensor: shape=(), dtype=int32, numpy=6>

# یک سطری

In [5]:
b=tf.constant([1,2,3,4,5,6])
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

#ماتریس 2 سطری

In [6]:
c=tf.constant([[1,2,3],[1,2,3]])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

# وقتی از دو بعد بیشتر باشد تنسور فلو میشود

In [7]:
d=tf.constant([[[1,2,3],[2,3,5]],[[1,2,3],[2,3,5]]])
d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 5]],

       [[1, 2, 3],
        [2, 3, 5]]], dtype=int32)>

# انجام عملیات ریاضی در تنسور فلو

# عمل جمع

In [8]:
a_1=tf.constant([1,2,3])
a_2=tf.constant([3,4,6])
sum_a=tf.add(a_1,a_2)
sum_a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 9], dtype=int32)>

# عمل تفریق

In [9]:
sub_a=tf.subtract(a_1,a_2)
sub_a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-2, -2, -3], dtype=int32)>

# عمل ضرب المان به المان

In [10]:
aa_1=tf.constant([[1,5],[1,6]])
aa_2=tf.constant([[1,2],[1,25]])
element_wize=tf.multiply(aa_1,aa_2)
element_wize

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  1,  10],
       [  1, 150]], dtype=int32)>

# عمل ضرب ماتریسی

In [11]:
mm=tf.matmul(aa_1,aa_2)
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  6, 127],
       [  7, 152]], dtype=int32)>

broadcasting

در اینجا تنسور فلو خودش عدد رو به صورت برداری به اندازه داده های متغیر دیگر تنظیم می کند به طوریکه هر عددی است رو در همه ایندکس ها در نظر می گیرد و ضرب در متغیر دیگری می کند

In [12]:
bc_1=tf.constant([1,2,3])
bc_2=tf.constant(5)
bc_n=bc_1*bc_2
bc_n

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10, 15], dtype=int32)>

# عمل تقسیم

In [13]:
div=tf.divide(aa_1,aa_2)
div


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1.  , 2.5 ],
       [1.  , 0.24]])>

وقتی در خروجی inf آمد یعنی بی نهایت

فقط در صورتی قابل تقسیم هستند که با هم از نظر برداری برابر باشن



# square
به توان 2 رسوندن

In [14]:
square_a=tf.constant([4,3,6,9,2])
squared_a=tf.square(square_a)
squared_a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9, 36, 81,  4], dtype=int32)>

# sqrt

جذر گرفتن

در صورتی که خطا داد باید داده ها را به فلوت تغییر دهید

 هم می توان یکی از داده ها را اعشاری نوشت

 هم می توان از روش زیر برای تغییر داده ها به فلوت استفاده کرد

In [15]:
# sqrt_a=tf.sqrt(square_a)
from numpy import float32
sqrt_a=tf.sqrt(tf.cast(square_a,dtype=float32))
sqrt_a

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([2.       , 1.7320508, 2.4494896, 3.       , 1.4142135],
      dtype=float32)>

#reshape

In [16]:
shape_a=tf.constant([1,2,3,4,5,6])
reshape_a=tf.reshape(shape_a,shape=(3,2))
reshape_a.shape
reshape_a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

# add dimention
اضافه کردن یک بعد

In [17]:
dim_a=tf.constant([1,2,3,4,5,6,7,8,9,0])
dim_b0=tf.expand_dims(dim_a,0)
dim_b0

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]], dtype=int32)>

In [18]:
dim_b1=tf.expand_dims(dim_a,1)
dim_b1

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]], dtype=int32)>

In [19]:
dim_b_1=tf.expand_dims(dim_a,-1)
dim_b_1

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]], dtype=int32)>

# بدست آوردن کمترین مقدار

In [20]:
m_a=tf.constant([[1,4,7,8,99],[2,2,4,555,32]])
min_a=tf.reduce_min(m_a)
min_a.numpy()


1

In [21]:
max_a=tf.reduce_max(m_a)
max_a.numpy()

555

In [22]:
min_a0=tf.reduce_min(m_a,axis=0)
min_a0.numpy()

array([ 1,  2,  4,  8, 32], dtype=int32)

In [23]:
max_a0=tf.reduce_max(m_a,axis=0)
max_a0.numpy()

array([  2,   4,   7, 555,  99], dtype=int32)

In [24]:
min_a1=tf.reduce_min(m_a,axis=1)
min_a1.numpy()

array([1, 2], dtype=int32)

In [25]:
max_a1=tf.reduce_max(m_a,axis=1)
max_a1.numpy()

array([ 99, 555], dtype=int32)

#　average

بدست آوردن میانکین

In [26]:
mean_a=tf.reduce_mean(m_a)
mean_a

<tf.Tensor: shape=(), dtype=int32, numpy=71>

In [27]:
m_a=tf.constant([[1,4,7,8,99],[2,2,4,555,32]],dtype=float32)
mean_a=tf.reduce_mean(m_a)
mean_a

<tf.Tensor: shape=(), dtype=float32, numpy=71.4>

# standard divition

بدست آوردن واریانس ، انحراف از معیار

In [28]:
std_div=tf.math.reduce_std(m_a)
std_div

<tf.Tensor: shape=(), dtype=float32, numpy=163.71451>

جمع همه داده ها با هم

In [29]:
sum_aa=tf.reduce_sum(m_a)
sum_aa

<tf.Tensor: shape=(), dtype=float32, numpy=714.0>