# classification

In [2]:
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import numpy as np

In [3]:
sparse_categorical_labels=np.array([1,0,2])
categorical_labels=to_categorical(sparse_categorical_labels)
print("sparse Categorical labels:")
print(sparse_categorical_labels)

print("\n Categolical labels:")
print(categorical_labels)

sparse Categorical labels:
[1 0 2]

 Categolical labels:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


باید در موقع کامپایل هم از گزینه categorical_crossentropy در قسمت loss استفاده بشه